# Generated by Django 5.0.7 on 2024-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
