# Generated by Django 5.0.7 on 2024-07-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_customuser_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
