# Generated by Django 5.0.7 on 2024-07-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_customuser_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.FloatField(max_length=20)),
                ('withdraw_amount', models.FloatField(max_length=20)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
