# Generated by Django 5.0.7 on 2024-07-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_withdraw_amount_usertransaction_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='amount',
        ),
    ]
