# Generated by Django 5.0.7 on 2024-07-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_usertransaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='withdraw',
            new_name='withdraw_amount',
        ),
    ]
