# Generated by Django 5.0.7 on 2024-07-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_withdraw_usertransaction_withdraw_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='withdraw_amount',
            new_name='withdraw',
        ),
    ]
