# Generated by Django 5.0.7 on 2024-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_withdraw_amount_usertransaction_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='get_balance',
            field=models.FloatField(default=0),
        ),
    ]
