# Generated by Django 5.0.7 on 2024-08-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_usertransaction_get_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='get_balance',
            new_name='check_balance',
        ),
    ]
