# Generated by Django 5.0.7 on 2024-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_get_balance_usertransaction_check_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='transaction_amount',
            field=models.FloatField(default=0),
        ),
    ]
