# Generated by Django 5.0.7 on 2024-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_usertransaction_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
