# Generated by Django 5.0.7 on 2024-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_usertransaction_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
