# Generated by Django 5.0.7 on 2024-08-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_remove_usertransaction_check_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='check_balance',
            field=models.FloatField(default=0),
        ),
    ]
