# Generated by Django 5.0.7 on 2024-08-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_remove_usertransaction_transaction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='initial_amount',
            new_name='security_deposit',
        ),
    ]
